import { TrackingPeriod, Units, Goal, UnitInputType } from "./models/Subject";

const a: import("./models/Subject").ISubject[] = [
  {
    id: "1",
    title: "sport",
    unitInputType: UnitInputType.number,
    creationDate: new Date("2019-01-01 17:00:00"),
    archived: false,
    TrackingPeriod: TrackingPeriod.Week,
    unit: Units.Times,
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: Goal.total,
    eventsArray: [],
    endDate: null,
    backgroundPic: null
  },
  {
    id: "2",
    title: "dates",
    unitInputType: UnitInputType.time,
    creationDate: new Date("2019-01-01 17:00:00"),
    archived: false,
    TrackingPeriod: TrackingPeriod.Week,
    unit: Units.Times,
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: Goal.total,
    eventsArray: [],
    endDate: null,
    backgroundPic: null
  },
  {
    id: "3",
    title: "sport",
    unitInputType: UnitInputType.number,
    creationDate: new Date("2019-01-01 17:00:00"),
    archived: false,
    TrackingPeriod: TrackingPeriod.Week,
    unit: Units.Times,
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: Goal.total,
    eventsArray: [],
    endDate: null,
    backgroundPic: null
  },
  {
    id: "4",
    title: "sport",
    unitInputType: UnitInputType.number,
    creationDate: new Date("2019-01-01 17:00:00"),
    archived: false,
    TrackingPeriod: TrackingPeriod.Week,
    unit: Units.Times,
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: Goal.total,
    eventsArray: [],
    endDate: null,
    backgroundPic: null
  },
  {
    id: "5",
    title: "sport",
    unitInputType: UnitInputType.number,
    creationDate: new Date("2019-01-01 17:00:00"),
    archived: false,
    TrackingPeriod: TrackingPeriod.Week,
    unit: Units.Times,
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: Goal.total,
    eventsArray: [],
    endDate: null,
    backgroundPic: null
  },
  {
    id: "6",
    title: "sport",
    unitInputType: UnitInputType.number,
    creationDate: new Date("2019-01-01 17:00:00"),
    archived: false,
    TrackingPeriod: TrackingPeriod.Week,
    unit: Units.Times,
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: Goal.total,
    eventsArray: [],
    endDate: null,
    backgroundPic: null
  }
];
export default a;
