export default [
  {
    id: 1,
    title: "sport",
    creationDate: "2019-01-01 17:00:00",
    archived: false,
    TrackingPeriod: "weeks",
    unit: "numbers",
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: "avg",
    eventsArray: [],
    endDate: null,
    backgroundPic: null
  },
  {
    id: 2,
    title: "books",
    creationDate: "2019-01-01 17:00:00",
    archived: false,
    TrackingPeriod: "weeks",
    unit: "numbers",
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: "avg",
    eventsArray: [],
    endDate: null,
    backgroundPic: null
  },
  {
    id: 3,
    title: "things",
    creationDate: "2019-01-01 17:00:00",
    archived: false,
    TrackingPeriod: "weeks",
    unit: "numbers",
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: "avg",
    eventsArray: [],
    endDate: null,
    backgroundPic: null
  },
  {
    id: 4,
    title: "running",
    creationDate: "2019-01-01 17:00:00",
    archived: false,
    TrackingPeriod: "weeks",
    unit: "numbers",
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: "avg",
    eventsArray: [],
    endDate: null,
    backgroundPic: null
  },
  {
    id: 5,
    title: "watching",
    creationDate: "2019-01-01 17:00:00",
    archived: false,
    TrackingPeriod: "weeks",
    unit: "numbers",
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: "avg",
    eventsArray: [],
    endDate: null,
    backgroundPic: null
  },
  {
    id: 6,
    title: "doing",
    creationDate: "2019-01-01 17:00:00",
    archived: false,
    TrackingPeriod: "weeks",
    unit: "numbers",
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: "avg",
    eventsArray: [],
    endDate: null,
    backgroundPic: null
  },
  {
    id: 7,
    title: "walking",
    creationDate: "2019-01-01 17:00:00",
    archived: false,
    TrackingPeriod: "weeks",
    unit: "numbers",
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: "avg",
    eventsArray: [],
    endDate: null,
    backgroundPic: null
  },
  {
    id: 8,
    title: "talking",
    creationDate: "2019-01-01 17:00:00",
    archived: false,
    TrackingPeriod: "weeks",
    unit: "numbers",
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: "avg",
    eventsArray: [],
    endDate: null,
    backgroundPic: null
  }
];
